// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

var TableNames = struct {
	Event     string
	EventUser string
	User      string
}{
	Event:     "event",
	EventUser: "event_user",
	User:      "user",
}
