// code generated by refiller. DO NOT EDIT.
// https://github.com/uhey22e/refiller
package refiller

import (
	"github.com/uhey22e/sqlboiler-restapi-example/boiler"
	"github.com/uhey22e/sqlboiler-restapi-example/restapi"
)

func NewRestapiEvent(src *boiler.Event) *restapi.Event {
	v := &restapi.Event{
		Description: src.Description,
		Id:          src.ID,
		Name:        src.Name,
	}
	return v
}

func NewBoilerEvent(src *restapi.Event) *boiler.Event {
	v := &boiler.Event{
		Description: src.Description,
		ID:          src.Id,
		Name:        src.Name,
	}
	return v
}

func FillRestapiEvent(dst *restapi.Event, src *boiler.Event) {
	dst.Description = src.Description
	dst.Id = src.ID
	dst.Name = src.Name
}

func FillBoilerEvent(dst *boiler.Event, src *restapi.Event) {
	dst.Description = src.Description
	dst.ID = src.Id
	dst.Name = src.Name
}
