// code generated by refiller. DO NOT EDIT.
// https://github.com/uhey22e/refiller
package refiller

import (
	"github.com/uhey22e/sqlboiler-restapi-example/boiler"
	"github.com/uhey22e/sqlboiler-restapi-example/restapi"
)

func NewRestapiUser(src *boiler.User) *restapi.User {
	v := &restapi.User{
		Id:   src.ID,
		Name: src.Name,
	}
	return v
}

func NewBoilerUser(src *restapi.User) *boiler.User {
	v := &boiler.User{
		ID:   src.Id,
		Name: src.Name,
	}
	return v
}

func FillRestapiUser(dst *restapi.User, src *boiler.User) {
	dst.Id = src.ID
	dst.Name = src.Name
}

func FillBoilerUser(dst *boiler.User, src *restapi.User) {
	dst.ID = src.Id
	dst.Name = src.Name
}
